ClothingJScript/Controllers/ClothingsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ClothingJScript.Models;

namespace ClothingJScript.Controllers
{
    public class ClothingsController : Controller
    {
        private ClothingDEntities2 db = new ClothingDEntities2();

        // GET: Clothings
        public ActionResult Index()
        {
            return View(db.Clothings.ToList());
        }

        // GET: Clothings/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Clothing clothing = db.Clothings.Find(id);
            if (clothing == null)
            {
                return HttpNotFound();
            }
            return View(clothing);
        }

        // GET: Clothings/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Clothings/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ClothingID,Type")] Clothing clothing)
        {
            if (ModelState.IsValid)
            {
                db.Clothings.Add(clothing);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(clothing);
        }

        // GET: Clothings/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Clothing clothing = db.Clothings.Find(id);
            if (clothing == null)
            {
                return HttpNotFound();
            }
            return View(clothing);
        }

        // POST: Clothings/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ClothingID,Type")] Clothing clothing)
        {
            if (ModelState.IsValid)
            {
                db.Entry(clothing).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(clothing);
        }

        // GET: Clothings/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Clothing clothing = db.Clothings.Find(id);
            if (clothing == null)
            {
                return HttpNotFound();
            }
            return View(clothing);
        }

        // POST: Clothings/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Clothing clothing = db.Clothings.Find(id);
            db.Clothings.Remove(clothing);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

ClothingJScript/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ClothingJScript.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

ClothingJScript/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

ClothingJScript/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

ClothingJScript/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}
<script src="~/ClothingScript.js"></script>

<div class="jumbotron">
    <video id="ad" onended= myFunction() controls autoplay><source src="~/Images/Together - State Farm® Commercial (youtubemp4.to).mp4" typeof="video/mp4"/></video>
</div>

<div class="row" id="HomeRow">
    <div class="col-md-6">
        <h2>Check out your clothes</h2>
        <p><a class="btn btn-default" href="~/Styles/Index">Check it out! &raquo;</a></p>
    </div>
    <div class="col-md-6" id="adrightlow">
        <img id="advertise" src="~/Images/adgif.gif" /> 
        <p><a class="btn btn-default" onclick="removal()">Remove ad &raquo;</a></p>
    </div>
</div>

<div class="row" id="Pyramid">
    <div class="col-md-4" id="wishlist" onclick="swap('wishlist', 'wlinput')">
        <h1>Click Me to Add Items to Your Wish List</h1>
    </div>
    <div class="col-md-4" id="wlinput" hidden>
        <form action="/action_page.php">
            Item Name:<br>
            <input type="text" name="name">
            <br>
            Item Brand:<br>
            <input type="text" name="Brand">
            <br>
            Item price:<br>
            <input type="text" name="Price">
            <br><br>
            <button type="button" class="btn" onclick="swap('wishlist','wlinput')">Submit</button>
        </form>
    </div>
    <div class="col-md-4" id="dropdown">
        <h2>Choose Your Favorite Brand of the Options Below</h2>
        <form id="itsaform">
            <select onclick="Populate()" id="favbrand">
                <option>Choose a brand</option>
            </select>
        </form>
    </div>
    <div class="col-md-4">
        <h2>View your clothes categories</h2>
        <p>@Html.ActionLink("Types of clothes", "Index", "Clothings")</p>
    </div>
</div>